locallibrary/locallibrary/catalog/urls.py
from django.urls import path
from catalog import views
from . import views
app_name='catalog'
urlpatterns = [
    path('',views.index,name='index'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote')
]

locallibrary/locallibrary/locallibrary/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls import include
from django.urls import path

from django.views.generic import RedirectView

from django.conf import settings
from django.conf.urls.static import static
'''Aqui é os ADM'''
urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('catalog/', include('catalog.urls')),
]

urlpatterns += [
    path('', RedirectView.as_view(url='/catalog/')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mytestsite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('migrations/',include('migrations.urls')),
    path('admin/', admin.site.urls),
]

catalog/models.py
from django.db import models

# Create your models here.

locallibrary/locallibrary/catalog/models.py
import datetime
from django.db import models

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    date_pub = models.DateField('data_publicacao')

    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.date_pub>=datetime.timezone.now()-datetime.timedelta(days=1)
class Choice(models.Model):
    question = models.ForeignKey(Question,on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

catalog/views.py
from django.shortcuts import render

# Create your views here.

locallibrary/locallibrary/catalog/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from .models import Question
from django.urls import reverse
# Create your views here.

def index(request):
    latest_question_list=Question.objects.order_by('-date_pub')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'catalog/index.html', context)
#def detail(request,question_id):
    return HttpResponse("Essa é a pergunta de número %s"%question_id)
def results(request,question_id):
    question = Question(pk=question_id)
    return render(request, 'catalog/results.html', {'question': question})
def vote(request,question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except KeyError:
        return render(request, 'catalog/vote.html', {
            'question': question,
            'error_message': "Nenhum item selecionado ainda",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('catalog:results', args=(question.id,)))

locallibrary/locallibrary/catalog/templates/catalog/index.html
<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="UTF-8">
    <title>Catalog</title>
</head>
<body>
   <h1>Lista de enquetes: </h1>
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'catalog:vote' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>sem catalagos.</p>
{% endif %}
</body>

locallibrary/locallibrary/catalog/templates/catalog/results.html
<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="UTF-8">
    <title>Resultado da Enquete</title>
</head>
<body>
<h1>Resultado da enquente votada: </h1>
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>
<h2>Próximo passo:</h2>
<a href="{% url 'catalog:vote' question.id %}">Votar novamente?</a><br>
<a href="{% url 'catalog:index' %}">voltar ao catalogo?</a>

</body>
</html>

locallibrary/locallibrary/catalog/templates/catalog/vote.html
<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="UTF-8">
    <title>Vote na enquete</title>
</head>
<body>
<h1>Votação da enquente:</h1>
<form action="{% url 'catalog:vote' question.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ question.question_text }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
</fieldset>
<input type="submit" value="Vote">
</form>


</body>
</html>